export const API_ENDPOINTS = {
  AUTH_LOGIN: "/auth/login",
  AUTH_REGISTER: "/auth/register",
  AUTH_ME: "/auth/me",
  BUSINESS_LOGIN: "/auth/business/login",
  BUSINESS_ME: "/auth/business/me",
  BUSINESS_LIST: "/business",
  BUSINESS_LIST_POST: "/business/list",
  BUSINESS_META_FILTERS: "/business/meta/filters",
  BUSINESS_BY_ID: (id: string) => `/business/${id}`,
  BUSINESS_CREATE: "/business",
  BUSINESS_STATS: "/business/stats/summary",
  BUSINESS_APPROVE: (id: string) => `/admin/approve/${id}`,
  BUSINESS_DELETE: (id: string) => `/business/${id}`,
  ADMIN_PENDING: "/admin/pending",
  ADMIN_BUSINESSES: "/admin/businesses",
  JOB_CREATE: "/jobs",
  JOB_LIST: "/jobs",
  JOB_LIST_POST: "/jobs/list",
  JOB_BY_ID: (id: string) => `/jobs/${id}`,
  JOB_CLOSE: (id: string) => `/jobs/${id}/close`,
  JOB_APPLY: (id: string) => `/jobs/${id}/apply`,
  JOB_BUSINESS_MINE: "/jobs/business/mine",
  JOB_STATS_SUMMARY: "/jobs/stats/summary",
  JOB_APPLICANTS_LIST: "/jobs/applicants/list",
  SEO: "/seo",
} as const;
